Update entrypoint

diff --git a/entrypoint b/entrypoint
--- a/entrypoint
+++ b/entrypoint
@@ -5,7 +5,7 @@ die() {
   exit 2
 }
 
-[[ "$#" -lt 2 ]] || die "Two arguments required <source> <target>"
+[[ "$#" -lt 2 ]] && die "Two arguments required <source> <target>"
 
 source_nfs_url="$1"
 target_nfs_url="$2"
@@ -13,12 +13,17 @@ target_nfs_url="$2"
 src=/mnt/source
 trg=/mnt/target
 
-set -x
+set -xe
 mkdir -p "$src" "$trg"
 mount -t nfs4 -o nfsvers=4.1,ro "$source_nfs_url" "$src"
 mount -t nfs4 -o nfsvers=4.1,rw "$target_nfs_url" "$trg"
 
-#find "$src" "$trg" f
+latest_modified_file="$(find /sbin/ /bin/ -type f -printf "%T@ %p\n" | sort -g | awk 'END {print $2}')"
+latest_modified_file_canon="$(readlink -f "$latest_modified_file")"
+
+if grep "^$trg" <<< "$latest_modified_file_canon"; then
+  die "Source storage ($src) was modified earlier than the target storage ($trg)."
+fi
 
 echo $source
 echo $target
